import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  Ban,
  Sparkles,
  Clock3,
  Wallet,
  Smartphone,
  Network,
  Gauge,
  Lock,
  PlusCircle,
  CheckCircle2,
  ShieldCheck,
  Share2,
  FileDown
} from 'lucide-react';
import { ReportGauge } from '../components/investigation/ReportGauge';
import { ReportNetwork } from '../components/investigation/ReportNetwork';

export const InvestigationReport: React.FC = () => {
  const navigate = useNavigate();
  const { caseId } = useParams<{ caseId: string }>();
  const activeCaseId = caseId || 'USR-RT990';

  const [customer, setCustomer] = useState<any>(null);
  const [analysis, setAnalysis] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Rajesh Kumar static demo data fallback
  const demoCustomer = {
    id: 'USR-RT990',
    name: 'Rajesh Kumar',
    defaults: { amount: 42500 }
  };

  const demoAnalysis = {
    trustScore: 42,
    decision: 'REJECT',
    reasons: [
      'Analysis indicates a sophisticated High Risk account takeover attempt involving cross-border transfers linked to dormant nodes in Southeast Asia.',
      'The behavioral signature of the recent $42,500 transaction deviates significantly from the customer’s footprint.',
      'Our neural network identified a direct correlation between the destination account and "Cluster Alpha"—a known syndicate.'
    ]
  };

  useEffect(() => {
    const loadReportData = async () => {
      try {
        setLoading(true);
        setError(null);

        if (activeCaseId === 'USR-RT990') {
          setCustomer(demoCustomer);
          setAnalysis(demoAnalysis);
          return;
        }

        const userResponse = await fetch(`http://localhost:3001/api/users/${activeCaseId}`);
        if (!userResponse.ok) {
          throw new Error('Customer report not found');
        }
        const userData = await userResponse.json();
        setCustomer(userData);

        const analyzePayload = {
          ...userData.defaults,
          userId: userData.id,
          amount: userData.defaults.amount,
          useCase: userData.defaults.useCase,
          location: userData.defaults.location ?? 'Mumbai',
          deviceType: userData.defaults.deviceType ?? 'mobile',
          loginHour: userData.defaults.loginHour ?? 9,
        };

        const analyzeResponse = await fetch('http://localhost:3001/api/analyze', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(analyzePayload),
        });

        if (!analyzeResponse.ok) {
          throw new Error('Analysis calculation failed');
        }

        const analyzeData = await analyzeResponse.json();
        setAnalysis({
          trustScore: analyzeData.trustScore,
          decision: analyzeData.decision === 'FLAG' ? 'REJECT' : analyzeData.decision === 'VERIFY' ? 'VERIFY' : 'APPROVE',
          reasons: analyzeData.reasons
        });
      } catch (err: any) {
        console.error('Failed loading report data', err);
        setError(err.message);
        setCustomer(demoCustomer);
        setAnalysis(demoAnalysis);
      } finally {
        setLoading(false);
      }
    };

    loadReportData();
  }, [activeCaseId]);

  if (loading) {
    return (
      <div className="flex min-h-[70vh] flex-col items-center justify-center gap-4 bg-[#0e0e0f] text-[#e5e2e3]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
        <p className="font-label-mono text-xs uppercase tracking-[0.3em] text-on-surface-variant">
          Loading report data
        </p>
      </div>
    );
  }

  return (
    <div className="w-full min-h-screen bg-[#0e0e0f] text-[#e5e2e3]">
      <main className="pt-8 px-grid-margin pb-32 max-w-[1600px] mx-auto space-y-8">
        
        {/* Section 1: Report Header */}
        <section className="py-10 border-b border-outline-variant/10 mb-12">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
            <div>
              <div className="mb-2">
                <h1 className="font-display-lg text-5xl md:text-[64px] text-on-surface font-extrabold tracking-tighter leading-none">
                  AI Investigation Report
                </h1>
                <p className="mt-4 text-on-surface-variant text-body-lg max-w-2xl leading-relaxed font-light">
                  This report was automatically generated by TrustShield AI after analysing customer behaviour, transaction history, relationship intelligence and fraud signals.
                </p>
              </div>
              <div className="flex flex-wrap gap-4 items-center mt-6">
                <div className="px-3 py-1 bg-surface-container-high rounded font-label-mono text-on-surface-variant text-xs">
                  INV ID: <span className="text-on-surface font-semibold">{activeCaseId.replace('USR-', '')}</span>
                </div>
                <div className="px-3 py-1 bg-surface-container-high rounded font-label-mono text-on-surface-variant text-xs">
                  Customer: <span className="text-on-surface font-semibold">{customer?.name || 'Rajesh Kumar'}</span>
                </div>
                <div className="flex items-center gap-2 px-3 py-1 bg-primary/10 border border-primary/20 rounded font-label-mono text-primary text-xs font-bold">
                  <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
                  STATUS: FINALIZED
                </div>
              </div>
            </div>
            <div className="flex flex-col items-end">
              <span className="font-label-mono text-on-surface-variant text-[10px] uppercase mb-1 tracking-wider">
                Final Recommendation
              </span>
              <div className={`px-8 py-4 rounded-xl border flex items-center gap-3 ${
                (analysis?.decision || 'REJECT') === 'APPROVE'
                  ? 'bg-primary/10 text-primary border-primary/20'
                  : (analysis?.decision || 'REJECT') === 'VERIFY'
                    ? 'bg-secondary/10 text-secondary border-secondary/20'
                    : 'bg-error-container text-on-error-container border-error/20'
              }`}>
                <Ban className="text-[32px] w-8 h-8" />
                <span className="font-headline-md text-headline-md font-extrabold uppercase tracking-widest text-2xl">
                  {analysis?.decision || 'REJECT'}
                </span>
              </div>
            </div>
          </div>
        </section>

        {/* Bento Grid Layout */}
        <div className="grid grid-cols-12 gap-grid-gutter">
          
          {/* Section 2: AI Executive Summary (8 columns) */}
          <div className="col-span-12 lg:col-span-8">
            <div className="glass-card p-stack-lg rounded-xl h-full relative overflow-hidden flex flex-col justify-between">
              <div className="absolute top-0 right-0 p-6 flex flex-col items-end gap-2">
                <div className="px-3 py-1 bg-primary/10 border border-primary/20 rounded-full flex items-center gap-2 text-[10px] font-label-mono text-primary font-bold">
                  <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span> AI GENERATED
                </div>
                <p className="text-[10px] text-on-surface-variant font-label-mono uppercase">
                  Generated: Oct 12, 04:32 PM
                </p>
              </div>
              <div>
                <div className="flex items-center gap-3 mb-8">
                  <Sparkles className="text-primary w-8 h-8" />
                  <h2 className="font-headline-md text-2xl font-bold">AI Executive Summary</h2>
                </div>
                <div className="space-y-8 text-on-surface-variant text-[18px] leading-[1.6] max-w-3xl p-2 font-light">
                  {activeCaseId === 'USR-RT990' ? (
                    <>
                      <p>
                        Analysis indicates a sophisticated <span className="text-error font-semibold">High Risk</span> account takeover attempt involving cross-border transfers linked to dormant nodes in Southeast Asia. The behavioral signature of the recent $42,500 transaction deviates significantly from the customer’s historical footprint, exhibiting patterns typical of automated laundering scripts.
                      </p>
                      <p>
                        Our neural network identified a direct correlation between the destination account and "Cluster Alpha"—a known syndicate linked to regional financial instability. Furthermore, the login attempt originated from an unverified IP range in Ho Chi Minh City, which has no documented association with the primary cardholder's travel history or residential records.
                      </p>
                      <p>
                        The convergence of these <span className="text-error font-semibold">Fraud Indicators</span> produces a high-confidence recommendation for immediate transaction reversal and account suspension pending deep identity verification. TrustShield AI assesses the <span className="text-primary font-semibold">Trust Score</span> likelihood of legitimate customer intent at less than 6%.
                      </p>
                    </>
                  ) : (
                    analysis?.reasons?.map((reason: string, idx: number) => (
                      <p key={idx}>{reason}</p>
                    ))
                  )}
                </div>
              </div>
              <div className="mt-12 flex gap-12 border-t border-outline-variant/10 pt-8">
                <div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant uppercase mb-1">Risk Vector</p>
                  <p className="text-error font-bold text-lg">Account Takeover (ATO)</p>
                </div>
                <div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant uppercase mb-1">Certainty</p>
                  <p className="text-primary font-bold text-lg">94% Confidence</p>
                </div>
                <div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant uppercase mb-1">Exposure</p>
                  <p className="text-on-surface font-bold text-lg">₹{(customer?.defaults?.amount || 42500).toLocaleString('en-IN')}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Section 4: Trust Score Summary (4 columns) */}
          <div className="col-span-12 lg:col-span-4">
            <div className="glass-card p-stack-lg rounded-xl h-full flex flex-col items-center justify-center text-center relative overflow-hidden">
              <div className="flex flex-col h-full items-center justify-between w-full">
                <div className="mb-8">
                  <h3 className="font-headline-md text-xl mb-2 font-bold">Integrated Trust Score</h3>
                  <p className="text-on-surface-variant text-sm font-light">Consolidated risk assessment across all intelligence vectors.</p>
                </div>
                
                <ReportGauge score={analysis?.trustScore ?? 42} status={analysis?.decision ?? "REJECT"} />

                <div className="w-full">
                  <div className="grid grid-cols-2 gap-8 w-full px-4 mb-8">
                    <div className="text-center">
                      <p className="text-[10px] font-label-mono text-on-surface-variant uppercase mb-1">AI Confidence</p>
                      <p className="text-primary font-bold text-xl">94%</p>
                    </div>
                    <div className="text-center">
                      <p className="text-[10px] font-label-mono text-on-surface-variant uppercase mb-1">Risk Category</p>
                      <p className={`${(analysis?.decision || 'REJECT') === 'APPROVE' ? 'text-primary' : (analysis?.decision || 'REJECT') === 'VERIFY' ? 'text-secondary' : 'text-error'} font-bold text-xl`}>
                        {(analysis?.decision || 'REJECT') === 'APPROVE' ? 'Low Risk' : (analysis?.decision || 'REJECT') === 'VERIFY' ? 'Medium Risk' : 'High Risk'}
                      </p>
                    </div>
                  </div>
                  <div className={`p-4 rounded-xl text-center border ${
                    (analysis?.decision || 'REJECT') === 'APPROVE'
                      ? 'bg-primary/10 border-primary/20 text-primary'
                      : (analysis?.decision || 'REJECT') === 'VERIFY'
                        ? 'bg-secondary/10 border-secondary/20 text-secondary'
                        : 'bg-error/10 border-error/20 text-error'
                  }`}>
                    <p className="font-bold uppercase tracking-widest text-xs">Final Recommendation: {analysis?.decision || 'REJECT'}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Section 3: Case Timeline (4 columns) */}
          <div className="col-span-12 lg:col-span-4">
            <div className="glass-card p-stack-lg rounded-xl h-full">
              <h3 className="font-headline-md text-[18px] mb-8 flex items-center gap-2 font-bold">
                <Clock3 className="text-primary w-5 h-5" />
                Case Timeline
              </h3>
              <div className="relative space-y-6 before:content-[''] before:absolute before:left-[11px] before:top-2 before:bottom-2 before:w-[1px] before:bg-outline-variant/20">
                
                <div className="relative pl-8 group">
                  <div className="absolute left-0 top-1 w-6 h-6 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary pulse-active"></div>
                  </div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant">OCT 12, 09:14 AM</p>
                  <p className="text-on-surface font-semibold text-sm">Transaction Received</p>
                  <p className="text-on-surface-variant text-[12px] font-light">Inbound transfer from External Bank (AE)</p>
                </div>

                <div className="relative pl-8">
                  <div className="absolute left-0 top-1 w-6 h-6 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary/40"></div>
                  </div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant">OCT 12, 09:15 AM</p>
                  <p className="text-on-surface font-semibold text-sm">Auto-Flag Triggered</p>
                  <p className="text-on-surface-variant text-[12px] font-light">Anomaly detected in geolocation logic</p>
                </div>

                <div className="relative pl-8">
                  <div className="absolute left-0 top-1 w-6 h-6 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary/40"></div>
                  </div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant">OCT 12, 09:20 AM</p>
                  <p className="text-on-surface font-semibold text-sm">AI Enrichment Started</p>
                  <p className="text-on-surface-variant text-[12px] font-light">Fetching external network datasets</p>
                </div>

                <div className="relative pl-8">
                  <div className="absolute left-0 top-1 w-6 h-6 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-error"></div>
                  </div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant">OCT 12, 10:02 AM</p>
                  <p className="text-on-surface font-semibold text-sm text-error">Cluster Alpha Linked</p>
                  <p className="text-on-surface-variant text-[12px] font-light">Destination confirmed high-risk node</p>
                </div>

                <div className="relative pl-8">
                  <div className="absolute left-0 top-1 w-6 h-6 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary/40"></div>
                  </div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant">OCT 12, 11:30 AM</p>
                  <p className="text-on-surface font-semibold text-sm">Analyst Assigned</p>
                  <p className="text-on-surface-variant text-[12px] font-light">Case routed to Level 2 Investigation</p>
                </div>

                <div className="relative pl-8">
                  <div className="absolute left-0 top-1 w-6 h-6 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary/40"></div>
                  </div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant">OCT 12, 02:45 PM</p>
                  <p className="text-on-surface font-semibold text-sm">Evidence Compiled</p>
                  <p className="text-on-surface-variant text-[12px] font-light">All 5 major vectors confirmed</p>
                </div>

                <div className="relative pl-8">
                  <div className="absolute left-0 top-1 w-6 h-6 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary/40"></div>
                  </div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant">OCT 12, 04:00 PM</p>
                  <p className="text-on-surface font-semibold text-sm">Compliance Review</p>
                  <p className="text-on-surface-variant text-[12px] font-light">Final secondary check completed</p>
                </div>

                <div className="relative pl-8">
                  <div className="absolute left-0 top-1 w-6 h-6 flex items-center justify-center">
                    <div className="w-1.5 h-1.5 rounded-full bg-primary"></div>
                  </div>
                  <p className="font-label-mono text-[10px] text-on-surface-variant">OCT 12, 04:32 PM</p>
                  <p className="text-on-surface font-semibold text-sm">Investigation Closed</p>
                  <p className="text-on-surface-variant text-[12px] font-light">Final report generated and locked</p>
                </div>

              </div>
            </div>
          </div>

          {/* Section 5: Evidence Summary (8 columns) */}
          <div className="col-span-12 lg:col-span-8">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-grid-gutter h-full">
              
              <div className="glass-card p-6 rounded-xl border-l-4 border-error flex flex-col justify-between">
                <div className="flex justify-between items-start mb-4">
                  <div className="flex items-center gap-2 text-on-surface-variant">
                    <Wallet className="text-error w-4 h-4" />
                    <span className="font-label-mono text-[10px] uppercase tracking-wider">Transaction</span>
                  </div>
                  <span className="px-2 py-0.5 bg-error/20 text-error text-[10px] font-bold rounded">HIGH SEVERITY</span>
                </div>
                <div>
                  <p className="text-2xl font-bold mb-1 font-display-lg text-white">$42,500.00</p>
                  <p className="text-on-surface-variant text-[11px] mb-4 font-light">900% above 30-day average. AI Confidence: 97%</p>
                </div>
                <button className="mt-auto text-primary text-xs flex items-center gap-1 hover:underline font-bold">
                  View Ledger <span className="text-[14px]">→</span>
                </button>
              </div>

              <div className="glass-card p-6 rounded-xl border-l-4 border-error flex flex-col justify-between">
                <div className="flex justify-between items-start mb-4">
                  <div className="flex items-center gap-2 text-on-surface-variant">
                    <Smartphone className="text-error w-4 h-4" />
                    <span className="font-label-mono text-[10px] uppercase tracking-wider">Device</span>
                  </div>
                  <span className="px-2 py-0.5 bg-error/20 text-error text-[10px] font-bold rounded">HIGH SEVERITY</span>
                </div>
                <div>
                  <p className="text-2xl font-bold mb-1 text-white">HCMC, Vietnam</p>
                  <p className="text-on-surface-variant text-[11px] mb-4 font-light">Unrecognized Linux environment. AI Confidence: 99%</p>
                </div>
                <button className="mt-auto text-primary text-xs flex items-center gap-1 hover:underline font-bold">
                  Geotag History <span className="text-[14px]">→</span>
                </button>
              </div>

              <div className="glass-card p-6 rounded-xl border-l-4 border-error flex flex-col justify-between">
                <div className="flex justify-between items-start mb-4">
                  <div className="flex items-center gap-2 text-on-surface-variant">
                    <Network className="text-error w-4 h-4" />
                    <span className="font-label-mono text-[10px] uppercase tracking-wider">Network</span>
                  </div>
                  <span className="px-2 py-0.5 bg-error/20 text-error text-[10px] font-bold rounded">CRITICAL</span>
                </div>
                <div>
                  <p className="text-2xl font-bold mb-1 text-white">Cluster Alpha</p>
                  <p className="text-on-surface-variant text-[11px] mb-4 font-light">Direct link to sanction list node. AI Confidence: 94%</p>
                </div>
                <button className="mt-auto text-primary text-xs flex items-center gap-1 hover:underline font-bold" onClick={() => navigate('/ai-copilot')}>
                  Graph Map <span className="text-[14px]">→</span>
                </button>
              </div>

              <div className="glass-card p-6 rounded-xl border-l-4 border-secondary flex flex-col justify-between">
                <div className="flex justify-between items-start mb-4">
                  <div className="flex items-center gap-2 text-on-surface-variant">
                    <Gauge className="text-secondary w-4 h-4" />
                    <span className="font-label-mono text-[10px] uppercase tracking-wider">Velocity</span>
                  </div>
                  <span className="px-2 py-0.5 bg-secondary/20 text-secondary text-[10px] font-bold rounded">MEDIUM</span>
                </div>
                <div>
                  <p className="text-2xl font-bold mb-1 text-white">Velocity Burst</p>
                  <p className="text-on-surface-variant text-[11px] mb-4 font-light">4 transactions in 120 seconds. AI Confidence: 88%</p>
                </div>
              </div>

              <div className="glass-card p-6 rounded-xl border-l-4 border-error flex flex-col justify-between">
                <div className="flex justify-between items-start mb-4">
                  <div className="flex items-center gap-2 text-on-surface-variant">
                    <Lock className="text-error w-4 h-4" />
                    <span className="font-label-mono text-[10px] uppercase tracking-wider">Access</span>
                  </div>
                  <span className="px-2 py-0.5 bg-error/20 text-error text-[10px] font-bold rounded">HIGH</span>
                </div>
                <div>
                  <p className="text-2xl font-bold mb-1 text-white">7 Attempts</p>
                  <p className="text-on-surface-variant text-[11px] mb-4 font-light">Brute-force profile match. AI Confidence: 92%</p>
                </div>
              </div>

              <div className="glass-card p-6 rounded-xl flex items-center justify-center text-center bg-primary/5 hover:bg-primary/10 cursor-pointer border-dashed border-2 border-primary/20 transition-all hover:scale-[1.02]">
                <div>
                  <PlusCircle className="text-primary w-10 h-10 mx-auto mb-2" />
                  <p className="text-on-surface font-semibold text-sm">Append New Signal</p>
                  <p className="text-on-surface-variant text-[10px] mt-1 font-light">Manual evidence upload</p>
                </div>
              </div>

            </div>
          </div>

          {/* Section 6: Relationship Network Snapshot (6 columns) */}
          {/* Section 6: Relationship Network Snapshot (6 columns) */}
          <div className="col-span-12 lg:col-span-6">
            <div className="glass-card p-stack-lg rounded-xl h-[400px] flex flex-col relative overflow-hidden justify-between">
              <div className="flex justify-between items-start mb-6">
                <div>
                  <h3 className="font-headline-md text-xl font-bold">Relationship Network Snapshot</h3>
                  <p className="text-on-surface-variant text-sm font-light">Topological view of people and organizations</p>
                </div>
                <button onClick={() => navigate(`/ai-copilot/${activeCaseId}`)} className="px-4 py-2 bg-surface-container-high hover:bg-surface-container-highest rounded text-sm transition-all border border-outline-variant/10 font-bold text-white">
                  Open Full Intelligence
                </button>
              </div>
              <ReportNetwork />
            </div>
          </div>

          {/* Section 7: Compliance Checklist (6 columns) */}
          <div className="col-span-12 lg:col-span-6">
            <div className="glass-card p-stack-lg rounded-xl h-[400px] flex flex-col justify-between">
              <div>
                <h3 className="font-headline-md text-[18px] mb-6 font-bold">Compliance Checklist</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  
                  <div className="p-4 bg-surface-container-low rounded-lg border border-outline-variant/10 flex items-center gap-3">
                    <CheckCircle2 className="text-primary w-5 h-5 shrink-0" />
                    <span className="text-on-surface text-sm">Identity Verified</span>
                  </div>

                  <div className="p-4 bg-surface-container-low rounded-lg border border-outline-variant/10 flex items-center gap-3">
                    <CheckCircle2 className="text-primary w-5 h-5 shrink-0" />
                    <span className="text-on-surface text-sm">AML Screening</span>
                  </div>

                  <div className="p-4 bg-surface-container-low rounded-lg border border-outline-variant/10 flex items-center gap-3">
                    <CheckCircle2 className="text-primary w-5 h-5 shrink-0" />
                    <span className="text-on-surface text-sm">Watchlist Check</span>
                  </div>

                  <div className="p-4 bg-surface-container-low rounded-lg border border-outline-variant/10 flex items-center gap-3">
                    <CheckCircle2 className="text-primary w-5 h-5 shrink-0" />
                    <span className="text-on-surface text-sm">Sanctions Match</span>
                  </div>

                  <div className="p-4 bg-surface-container-low rounded-lg border border-outline-variant/10 flex items-center gap-3">
                    <CheckCircle2 className="text-primary w-5 h-5 shrink-0" />
                    <span className="text-on-surface text-sm">PEP Verification</span>
                  </div>

                  <div className="p-4 bg-surface-container-low rounded-lg border border-outline-variant/10 flex items-center gap-3">
                    <CheckCircle2 className="text-primary w-5 h-5 shrink-0" />
                    <span className="text-on-surface text-sm">Document Audit</span>
                  </div>

                </div>
              </div>
              <div className="mt-8 p-4 bg-primary/5 border border-primary/10 rounded-lg">
                <p className="text-xs italic text-on-surface-variant font-light">
                  "Automated compliance checks completed via TrustShield Protocol v4.2. No manual intervention required for basic screening stages."
                </p>
              </div>
            </div>
          </div>

          {/* Section 8: Final Recommendation Explanation (12 columns) */}
          <div className="col-span-12">
            <div className="glass-card p-stack-lg rounded-xl border-l-8 border-error">
              <div className="flex flex-col md:flex-row gap-12 items-center md:items-start">
                <div className="shrink-0 text-center md:text-left">
                  <p className="font-label-mono text-on-surface-variant uppercase text-xs tracking-widest mb-4">
                    Final Protocol Command
                  </p>
                  <div className="text-error text-7xl md:text-[100px] font-extrabold uppercase tracking-tighter leading-none mb-2 drop-shadow-[0_0_30px_rgba(255,180,174,0.2)] font-display-lg">
                    {analysis?.decision || 'REJECT'}
                  </div>
                </div>
                <div className="flex-1 border-l-0 md:border-l border-outline-variant/20 md:pl-12">
                  <h4 className="font-headline-md text-2xl text-on-surface mb-6 font-bold">
                    Internal Intelligence Decision Memo
                  </h4>
                  <p className="text-on-surface-variant leading-relaxed text-lg font-light">
                    Based on the confluence of high-velocity patterns, geographic inconsistency, and direct linkage to high-risk financial clusters, the TrustShield Intelligence Engine mandates an immediate {analysis?.decision || 'REJECT'} decision. The account is flagged for compliance monitoring and submission to regional authorities. Any attempt to override this decision requires Level 3 Principal approval and documented risk assumption.
                  </p>
                </div>
              </div>
            </div>
          </div>

        </div>

      </main>

      {/* Section 9: Report Actions (Bottom Dock) */}
      <div className="fixed bottom-0 left-16 right-0 h-24 bg-[#131314]/80 backdrop-blur-xl border-t border-outline-variant/10 flex items-center justify-between px-grid-margin z-30">
        <div className="flex items-center gap-6">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center border border-primary/20">
              <ShieldCheck className="text-primary w-5 h-5" />
            </div>
            <div>
              <p className="text-[10px] text-on-surface-variant uppercase font-label-mono leading-none mb-1 tracking-wider">
                Verified By
              </p>
              <p className="text-on-surface font-bold text-sm">T-Shield Sentinel 9</p>
            </div>
          </div>
        </div>
        <div className="flex gap-3">
          <button onClick={() => navigate(`/customer/${activeCaseId}`)} className="px-4 py-2.5 bg-surface-container-high hover:bg-surface-container-highest text-on-surface rounded-lg text-xs font-bold transition-all border border-outline-variant/10">
            Return to Profile
          </button>
          <button onClick={() => navigate(`/investigation/${activeCaseId}`)} className="px-4 py-2.5 bg-surface-container-high hover:bg-surface-container-highest text-on-surface rounded-lg text-xs font-bold transition-all border border-outline-variant/10">
            Open Investigation
          </button>
          <button className="px-4 py-2.5 bg-surface-container-high hover:bg-surface-container-highest text-on-surface rounded-lg text-xs font-bold transition-all border border-outline-variant/10">
            Export JSON
          </button>
          <button className="flex items-center gap-2 px-4 py-2.5 bg-surface-container-high hover:bg-surface-container-highest text-on-surface rounded-lg text-xs font-bold transition-all border border-outline-variant/10">
            <Share2 className="w-3.5 h-3.5" /> Share
          </button>
          <button className="flex items-center gap-2 px-8 py-2.5 bg-primary text-on-primary rounded-lg text-xs font-bold transition-all hover:shadow-[0_0_20px_rgba(75,226,119,0.3)] active:scale-95">
            <FileDown className="w-3.5 h-3.5" /> Generate PDF Report
          </button>
        </div>
      </div>

      {/* Footer */}
      <footer className="pl-16 px-grid-margin py-12 border-t border-outline-variant/10 bg-surface-container-lowest">
        <div className="max-w-[1600px] mx-auto flex flex-col md:flex-row justify-between items-start gap-8">
          <div className="max-w-2xl">
            <p className="text-xs text-on-surface-variant leading-relaxed font-light">
              This report was automatically generated by TrustShield AI using explainable AI models. Every recommendation is supported by an auditable reasoning trail and can be reviewed by investigators and compliance teams. TrustShield AI is a registered trademark of TrustShield Intelligence Systems.
            </p>
          </div>
          <div className="flex gap-8 font-label-mono text-[9px] uppercase tracking-widest text-on-surface-variant font-semibold">
            <span>Protocol v4.2.0</span>
            <span>Model: TS-OMEGA-9</span>
            <span>Confidential</span>
          </div>
        </div>
      </footer>
    </div>
  );
};
